### PR TITLE
Updated with rhatcher changes

### PR DESCRIPTION
**Pull request by Noah-Everett**
I changed out all the files I had from the most recent edits with Robert Hatcher. I did not touch anything that wasn't in my version of the most resent one.

### CODE REVIEW

**Comment by marc1uk** [comment]
Thanks Noah,
Can i ask that to keep the codebase clean you simply delete the obsolete files rather than renaming them with an `_obsolete` suffix? Those files aren't doing anything now, and they're in the git history if they need to be retrieved or referenced in the future.

There are also a small number of changes that clobber features introduced since the version you're working with: in particular recording genie events that occur in the detector, but not necessarily the water. It's a very crude method but that's what [this](https://github.com/ANNIEsoft/anniedirt/pull/1/files#diff-065c48e10e45b0e8e5f14545babf9c64bff66a5d9b2a6ba3ed3eb0f6eec92e51L181) and [this](https://github.com/ANNIEsoft/anniedirt/pull/1/files#diff-8edaaccf2a60da2d3b4688cd64e10b58790f840bab1a5d792735afe4134fcbf5L100) is doing, so unless it breaks something I'd prefer to keep it in.

I also spot that you've removed the [src/annie_v04.gdml](https://github.com/ANNIEsoft/anniedirt/pull/1/files#diff-c04578e793225bad14bf085c007c89fff5f6237221a22f010bdb30ac34702df6L1) geometry file and instead hard-code a [reference to a file](https://github.com/ANNIEsoft/anniedirt/pull/1/files#diff-8edaaccf2a60da2d3b4688cd64e10b58790f840bab1a5d792735afe4134fcbf5L100) outside the repository, so can we revert that please?

As a minor pet-peeve please also try not to introduce [white-space changes](https://github.com/ANNIEsoft/anniedirt/pull/1/files#diff-1e7de1ae2d059d21e1dd75d5812d5a34b0222cef273b7c3a2af62eb747f9d20aL9), since they just result in noise in the git diffs.

**Comment by marc1uk** [comment]
Finally, i notice you're merging these changes into the genie_2_8_6 branch.
Is that the version of genie you were using? If not, please ensure you're making a PR against the right branch.

**Comment by Noah-Everett** [comment]
Okay. I believe there should be support for insomethinginteresting. As far as the hard coded geometry files is concerned, I believe that is just as arbitrary as the other initially set command line options and should be set by the user at run time as a command line option. I do not have a file in that location when I use this program, I set it to the geometry I want and it works fine. Sorry about the white spaces. I was just uploading the changes Robert Hatcher made.

**Comment by Noah-Everett** [comment]
Oh, I forgot to mention that I don't want to merge into the 2.8.6 branch. I created a new 2.12.10 branch but I don't know how to merge into this branch on the ANNIESoft repo as it doesn't exit.

**Comment by marc1uk** [comment]
> I do not have a file in that location when I use this program

The geometry file, which is required for this application to run, is [in the repository](https://github.com/ANNIEsoft/anniedirt/blob/genie_2_8_6/src/annie_v04.gdml), but your pull request deletes it. 
Screenshot_2022-11-16_12-02-11
I don't disagree that users may wish to override the geometry file chosen from the command line, but i think removing it from the repository is a bad idea.

> I created a new 2.12.10 branch but I don't know how to merge into this branch on the ANNIESoft repo as it doesn't exit.

We have a [genie 2_12 branch](https://github.com/ANNIEsoft/anniedirt/tree/genie_2_12). To make a PR agains that, choose the branch when creating the PR:

Screenshot_2022-11-16_12-00-06

**Comment by Noah-Everett** [comment]
Sorry about the branch issue. I did not recognize that 2_12 branch existed

**Pull request closed without merging**
